services:
  - type: web
    name: torrent-studio-render-seedr
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SEEDR_API_TOKEN
        sync: false
      - key: SEEDR_LIBRARY_FOLDER_ID
        value: "88718944"
      - key: SEEDR_MAX_SIZE_GB
        value: "5"
