services:
  - type: web
    name: torrent-studio-render-seedr
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SEEDR_API_TOKEN
        sync: false
      - key: SEEDR_LIBRARY_FOLDER_ID
        value: "88718944"
      - key: SEEDR_MAX_SIZE_GB
        value: "5"
